### ISSUE TITLE
Use SCORPION and build networks on mouse scRNA-seq data

### ISSUE THREAD

**Issue by somsomikim** [kuijjerlab/SCORPION#1]
Hi,

I would like to apply SCORPION on my mouse scRNA-seq data, but I think scorpionTest only includes example prior networks for homo sapiens. May I please have detailed source files or methods to build prior networks for mouse? Or was there any issues related to applying SCORPION to other species?

I've read the paragraph related to my question, but can I have any details of analysis codes or databases?
# (Methods)
Prior network generation
To generate the unrefined regulatory networks that serve as prior for the message-passing algorithm, we downloaded the promoter region coordinates for each gene from ENSEMBL. We then used TABIX to retrieve the motif footprints and associated MOODS match scores located within 1,000-bp before the transcription start site of each gene from ref. [40](https://www.nature.com/articles/s43588-024-00597-5#ref-CR40). When multiple matches of the same transcription factor footprints were found, the highest value was retained for the study. The data on transcription factor protein–protein interactions and their associated scores were obtained from the STRING database version 11.5[39](https://www.nature.com/articles/s43588-024-00597-5#ref-CR39).
#

Thank you.

Somi

**Comment by mararie** [comment]
Hi! You can find a prior network for mouse on my colleague's website:
https://sites.google.com/a/channing.harvard.edu/kimberlyglass/tools/resources
Maybe that would be the easiest, as it can be used directly?
Best, Marieke

**Comment by somsomikim** [comment]
Thanks, Marieke!

I have downloaded motif information from the link that you've shared and it worked :)

Additionally, I've used mouse PPI network, MIPPIE, downloaded from https://cbdm-01.zdv.uni-mainz.de/~galanisl/mippie/download.php.
If there is any better options or any other databases, please share them with us.
Many thanks!

Best,
Somi
